INFO     user_service:user_service.py:20 Starting the process to create a user.
INFO     auth_service:authentification.py:10 Initializing Auth class.
INFO     auth_service:authentification.py:17 Loading credential configuration from 'credentials.json'.
INFO     auth_service:authentification.py:13 Auth class initialized successfully.
INFO     auth_service:authentification.py:37 Building headers for user type: 'valid_user'
INFO     auth_service:authentification.py:28 Fetching user details for user type: 'valid_user'
INFO     auth_manager:auth_manager.py:18 Building headers for user: admin
INFO     auth_manager:auth_manager.py:9 Encoding credentials for user: admin
INFO     auth_manager:auth_manager.py:28 Headers build successfully for user: admin
INFO     auth_service:authentification.py:47 Headers successfully built for user type: 'valid_user'
INFO     api_manager:api_manager.py:24 POST Request URL: https://testing.espocloud.com/api/v1/User | {'Espo-Authorization': 'YWRtaW46NjI0MjkyNTU=', 'X-Api-Key': 'f542db99f09e823eeb14cd558f104fef', 'Content-Type': 'application/json'}
INFO     api_manager:api_manager.py:26 Response Status Code: 400
INFO     api_manager:api_manager.py:27 Response: {"messageTranslation":{"label":"validationFailure","scope":null,"data":{"field":"userName","type":"maxLength"}}}
INFO     user_service:user_service.py:24 Finished processing the create user request.
INFO     status_code_assertion:status_code_assertion.py:35 Validating status code 400 for response with URL: https://testing.espocloud.com/api/v1/User
INFO     status_code_assertion:status_code_assertion.py:40 Status code 400 validated successfully.