INFO     user_hooks:user_hooks.py:9 Setting up for adding a user.
INFO     user_service:user_service.py:20 Starting the process to create a user.
INFO     auth_service:authentification.py:10 Initializing Auth class.
INFO     auth_service:authentification.py:17 Loading credential configuration from 'credentials.json'.
INFO     auth_service:authentification.py:13 Auth class initialized successfully.
INFO     auth_service:authentification.py:37 Building headers for user type: 'valid_user'
INFO     auth_service:authentification.py:28 Fetching user details for user type: 'valid_user'
INFO     auth_manager:auth_manager.py:18 Building headers for user: admin
INFO     auth_manager:auth_manager.py:9 Encoding credentials for user: admin
INFO     auth_manager:auth_manager.py:28 Headers build successfully for user: admin
INFO     auth_service:authentification.py:47 Headers successfully built for user type: 'valid_user'
INFO     api_manager:api_request.py:23 POST Request URL: https://testing.espocloud.com/api/v1/User | {'Espo-Authorization': 'YWRtaW46NjI0MjkyNTU=', 'X-Api-Key': 'f542db99f09e823eeb14cd558f104fef', 'Content-Type': 'application/json'}
INFO     api_manager:api_request.py:25 Response Status Code: 200
INFO     user_service:user_service.py:24 Finished processing the create user request.
INFO     user_service:user_service.py:11 Starting the process to get the user list.
INFO     auth_service:authentification.py:10 Initializing Auth class.
INFO     auth_service:authentification.py:17 Loading credential configuration from 'credentials.json'.
INFO     auth_service:authentification.py:13 Auth class initialized successfully.
INFO     auth_service:authentification.py:37 Building headers for user type: 'valid_user'
INFO     auth_service:authentification.py:28 Fetching user details for user type: 'valid_user'
INFO     auth_manager:auth_manager.py:18 Building headers for user: admin
INFO     auth_manager:auth_manager.py:9 Encoding credentials for user: admin
INFO     auth_manager:auth_manager.py:28 Headers build successfully for user: admin
INFO     auth_service:authentification.py:47 Headers successfully built for user type: 'valid_user'
INFO     api_manager:api_request.py:12 GET Request URL: https://testing.espocloud.com/api/v1/User?userType=internal&select=isActive%2CemailAddressIsOptedOut%2CemailAddressIsInvalid%2CemailAddress%2CemailAddressData%2Ctitle%2CuserName%2CsalutationName%2CfirstName%2ClastName%2CmiddleName%2Cname&maxSize=20&offset=0&orderBy=userName&order=asc | {'Espo-Authorization': 'YWRtaW46NjI0MjkyNTU=', 'X-Api-Key': 'f542db99f09e823eeb14cd558f104fef'}
INFO     api_manager:api_request.py:14 Response Status Code: 200
INFO     user_service:user_service.py:15 Finished processing the user list request.
INFO     status_code_assertion:status_code_assertion.py:9 Validating status code 200 for response with URL: https://testing.espocloud.com/api/v1/User?userType=internal&select=isActive%2CemailAddressIsOptedOut%2CemailAddressIsInvalid%2CemailAddress%2CemailAddressData%2Ctitle%2CuserName%2CsalutationName%2CfirstName%2ClastName%2CmiddleName%2Cname&maxSize=20&offset=0&orderBy=userName&order=asc
INFO     status_code_assertion:status_code_assertion.py:14 Status code 200 validated successfully.
INFO     status_code_assertion:status_code_assertion.py:16 Response body is not empty.
INFO     schema_assertion:schema_assertion.py:41 Validating response JSON against 'list_schema.json'
INFO     schema_assertion:schema_assertion.py:16 Loaded schema: list_schema.json
INFO     schema_assertion:schema_assertion.py:26 JSON schema validation for 'list_schema.json' passed.
INFO     content_assertion:general_assertion.py:24 Validating 'list' is not empty. Found 7 items.
INFO     content_assertion:general_assertion.py:13 Validating 'total' is greater than 0. Found: 7
INFO     content_assertion:general_assertion.py:189 Validating that the value '670404869582fc470' is present in the field 'id' of the response list.
INFO     content_assertion:general_assertion.py:193 Value '670404869582fc470' successfully validated in the field 'id' of the response list.
INFO     content_assertion:general_assertion.py:237 Validating that the value '6703f58e9acadd548' is NOT present in the field 'id' of the response list.
INFO     content_assertion:general_assertion.py:241 Value '6703f58e9acadd548' is not present in the field 'id' of the response list, as expected.