{"uid":"59f2c1974ba85f20","name":"test_update_user_with_nonexistent_user_id_returns_404","fullName":"test.users.test_put_user#test_update_user_with_nonexistent_user_id_returns_404","historyId":"d86ffcdc559e5e5c2432d8136a933838","time":{"start":1726087520915,"stop":1726087521061,"duration":146},"status":"failed","statusMessage":"AssertionError: Expected status code 404, but got 403. Response text:","statusTrace":"@pytest.mark.updateuser\n    def test_update_user_with_nonexistent_user_id_returns_404():\n        url = EndpointUser.get_user_id(\"nonexistent_id\")\n        data = create_user_data()\n        response = UserService.update_user(url, data)\n>       AssertionManager.assert_status_code_404(response)\n\ntest/users/test_put_user.py:333: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [403]>\n\n    @staticmethod\n    def assert_status_code_404(response):\n        logger.info(f\"Validating status code 404 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 404, (\n                f\"Expected status code 404, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 404, but got 403. Response text:\n\ncore/assertions/status_code_assertion.py:61: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1726087466101,"stop":1726087466118,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: Expected status code 404, but got 403. Response text:","statusTrace":"@pytest.mark.updateuser\n    def test_update_user_with_nonexistent_user_id_returns_404():\n        url = EndpointUser.get_user_id(\"nonexistent_id\")\n        data = create_user_data()\n        response = UserService.update_user(url, data)\n>       AssertionManager.assert_status_code_404(response)\n\ntest/users/test_put_user.py:333: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [403]>\n\n    @staticmethod\n    def assert_status_code_404(response):\n        logger.info(f\"Validating status code 404 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 404, (\n                f\"Expected status code 404, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 404, but got 403. Response text:\n\ncore/assertions/status_code_assertion.py:61: AssertionError","steps":[],"attachments":[{"uid":"119dc76f52bef3c7","name":"log","source":"119dc76f52bef3c7.txt","type":"text/plain","size":2879},{"uid":"b9d23973248f550b","name":"stderr","source":"b9d23973248f550b.txt","type":"text/plain","size":3023}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[],"labels":[{"name":"tag","value":"updateuser"},{"name":"parentSuite","value":"test.users"},{"name":"suite","value":"test_put_user"},{"name":"host","value":"fv-az1435-834"},{"name":"thread","value":"2084-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.users.test_put_user"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["updateuser"]},"source":"59f2c1974ba85f20.json","parameterValues":[]}