{"uid":"950ec79a7c430e71","name":"test_view_deleted_team_returns_404","fullName":"test.teams.test_get_team#test_view_deleted_team_returns_404","historyId":"3fea3e59d795af85e5e11d6bcdacd986","time":{"start":1728317245400,"stop":1728317246037,"duration":637},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 404, but got 200. Response text: {\"id\":\"6704073d56dc52d3a\",\"name\":\"Team test see\",\"deleted\":true,\"positionList\":[\"Scrum Master\",\"Qa\",\"Designer\"],\"createdAt\":\"2024-10-07 16:07:25\",\"modifiedAt\":\"2024-10-07 16:07:25\",\"rolesIds\":[\"6703f64ba26bb589d\",\"6703f804da5feb1b0\"],\"rolesNames\":{\"6703f64ba26bb589d\":\"Administrador\",\"6703f804da5feb1b0\":\"Mortal\"},\"layoutSetId\":\"6703f89e1996ee098\",\"layoutSetName\":\"layaout\",\"workingTimeCalendarId\":\"6703f8ace83cd97ed\",\"workingTimeCalendarName\":\"calendar\"}","statusTrace":"setup_teardown_team_module = {'createdAt': '2024-10-07 16:07:25', 'deleted': False, 'id': '6704073d56dc52d3a', 'layoutSetId': '6703f89e1996ee098', ...}\n\n    @pytest.mark.viewteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_view_deleted_team_returns_404(setup_teardown_team_module):\n        team = setup_teardown_team_module\n        url = EndpointTeams.get_team_id(team['id'])\n        TeamService.delete_team(url)\n        response = TeamService.view_team(url)\n>       AssertionManager.assert_status_code_404(response)\n\ntest/teams/test_get_team.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>\n\n    @staticmethod\n    def assert_status_code_404(response):\n        logger.info(f\"Validating status code 404 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 404, (\n                f\"Expected status code 404, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 404, but got 200. Response text: {\"id\":\"6704073d56dc52d3a\",\"name\":\"Team test see\",\"deleted\":true,\"positionList\":[\"Scrum Master\",\"Qa\",\"Designer\"],\"createdAt\":\"2024-10-07 16:07:25\",\"modifiedAt\":\"2024-10-07 16:07:25\",\"rolesIds\":[\"6703f64ba26bb589d\",\"6703f804da5feb1b0\"],\"rolesNames\":{\"6703f64ba26bb589d\":\"Administrador\",\"6703f804da5feb1b0\":\"Mortal\"},\"layoutSetId\":\"6703f89e1996ee098\",\"layoutSetName\":\"layaout\",\"workingTimeCalendarId\":\"6703f8ace83cd97ed\",\"workingTimeCalendarName\":\"calendar\"}\n\ncore/assertions/status_code_assertion.py:61: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1728317231286,"stop":1728317231302,"duration":16},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_team_module","time":{"start":1728317245068,"stop":1728317245399,"duration":331},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 404, but got 200. Response text: {\"id\":\"6704073d56dc52d3a\",\"name\":\"Team test see\",\"deleted\":true,\"positionList\":[\"Scrum Master\",\"Qa\",\"Designer\"],\"createdAt\":\"2024-10-07 16:07:25\",\"modifiedAt\":\"2024-10-07 16:07:25\",\"rolesIds\":[\"6703f64ba26bb589d\",\"6703f804da5feb1b0\"],\"rolesNames\":{\"6703f64ba26bb589d\":\"Administrador\",\"6703f804da5feb1b0\":\"Mortal\"},\"layoutSetId\":\"6703f89e1996ee098\",\"layoutSetName\":\"layaout\",\"workingTimeCalendarId\":\"6703f8ace83cd97ed\",\"workingTimeCalendarName\":\"calendar\"}","statusTrace":"setup_teardown_team_module = {'createdAt': '2024-10-07 16:07:25', 'deleted': False, 'id': '6704073d56dc52d3a', 'layoutSetId': '6703f89e1996ee098', ...}\n\n    @pytest.mark.viewteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_view_deleted_team_returns_404(setup_teardown_team_module):\n        team = setup_teardown_team_module\n        url = EndpointTeams.get_team_id(team['id'])\n        TeamService.delete_team(url)\n        response = TeamService.view_team(url)\n>       AssertionManager.assert_status_code_404(response)\n\ntest/teams/test_get_team.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>\n\n    @staticmethod\n    def assert_status_code_404(response):\n        logger.info(f\"Validating status code 404 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 404, (\n                f\"Expected status code 404, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 404, but got 200. Response text: {\"id\":\"6704073d56dc52d3a\",\"name\":\"Team test see\",\"deleted\":true,\"positionList\":[\"Scrum Master\",\"Qa\",\"Designer\"],\"createdAt\":\"2024-10-07 16:07:25\",\"modifiedAt\":\"2024-10-07 16:07:25\",\"rolesIds\":[\"6703f64ba26bb589d\",\"6703f804da5feb1b0\"],\"rolesNames\":{\"6703f64ba26bb589d\":\"Administrador\",\"6703f804da5feb1b0\":\"Mortal\"},\"layoutSetId\":\"6703f89e1996ee098\",\"layoutSetName\":\"layaout\",\"workingTimeCalendarId\":\"6703f8ace83cd97ed\",\"workingTimeCalendarName\":\"calendar\"}\n\ncore/assertions/status_code_assertion.py:61: AssertionError","steps":[],"attachments":[{"uid":"4aa7fbe25a53ceee","name":"log","source":"4aa7fbe25a53ceee.txt","type":"text/plain","size":5871},{"uid":"6c804abe5030cd0c","name":"stderr","source":"6c804abe5030cd0c.txt","type":"text/plain","size":6160}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[{"name":"setup_teardown_team_module::0","time":{"start":1728317246068,"stop":1728317246374,"duration":306},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"viewteam"},{"name":"parentSuite","value":"test.teams"},{"name":"suite","value":"test_get_team"},{"name":"host","value":"fv-az2021-400"},{"name":"thread","value":"2070-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.teams.test_get_team"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["viewteam","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"950ec79a7c430e71.json","parameterValues":[]}