{"uid":"dd6c484b120c6d6b","name":"test_update_team_with_empty_name_returns_400","fullName":"test.teams.test_put_team#test_update_team_with_empty_name_returns_400","historyId":"6ae4b307c4743ab6f66268eae49e8c27","time":{"start":1725939985843,"stop":1725939986209,"duration":366},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400, but got 200. Response text: {\"id\":\"66dfc111bfc850aa0\",\"name\":null,\"deleted\":false,\"positionList\":[\"Qa\",\"Designer\",\"Product Owner\"],\"createdAt\":\"2024-09-10 03:46:25\",\"modifiedAt\":\"2024-09-10 03:46:26\",\"rolesIds\":[\"52bd3ee937361\",\"52bc41359084d\"],\"rolesNames\":{\"52bd3ee937361\":\"Sales\",\"52bc41359084d\":\"Sales Manager\"},\"layoutSetId\":\"66d8f8ff4f1c23bca\",\"layoutSetName\":\"Layaout 1\",\"workingTimeCalendarId\":\"66d8f90b424428d1b\",\"workingTimeCalendarName\":\"calendar\"}","statusTrace":"setup_teardown_team = {'createdAt': '2024-09-10 03:46:25', 'deleted': False, 'id': '66dfc111bfc850aa0', 'layoutSetId': '66d8f8ff4f1c23bca', ...}\n\n    @pytest.mark.updateteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_update_team_with_empty_name_returns_400(setup_teardown_team):\n        team1 = setup_teardown_team\n        url = EndpointTeams.get_team_id(team1['id'])\n        data = create_team_data(\n            name=\"\")\n        response = TeamService.update_team(url, data)\n>       AssertionManager.assert_status_code_400(response)\n\ntest/teams/test_put_team.py:46: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n        logger.info(f\"Validating status code 400 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 400, (\n                f\"Expected status code 400, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 400, but got 200. Response text: {\"id\":\"66dfc111bfc850aa0\",\"name\":null,\"deleted\":false,\"positionList\":[\"Qa\",\"Designer\",\"Product Owner\"],\"createdAt\":\"2024-09-10 03:46:25\",\"modifiedAt\":\"2024-09-10 03:46:26\",\"rolesIds\":[\"52bd3ee937361\",\"52bc41359084d\"],\"rolesNames\":{\"52bd3ee937361\":\"Sales\",\"52bc41359084d\":\"Sales Manager\"},\"layoutSetId\":\"66d8f8ff4f1c23bca\",\"layoutSetName\":\"Layaout 1\",\"workingTimeCalendarId\":\"66d8f90b424428d1b\",\"workingTimeCalendarName\":\"calendar\"}\n\ncore/assertions/status_code_assertion.py:37: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1725939934214,"stop":1725939934231,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_team","time":{"start":1725939985476,"stop":1725939985842,"duration":366},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_team","time":{"start":1725940001178,"stop":1725940001543,"duration":365},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400, but got 200. Response text: {\"id\":\"66dfc111bfc850aa0\",\"name\":null,\"deleted\":false,\"positionList\":[\"Qa\",\"Designer\",\"Product Owner\"],\"createdAt\":\"2024-09-10 03:46:25\",\"modifiedAt\":\"2024-09-10 03:46:26\",\"rolesIds\":[\"52bd3ee937361\",\"52bc41359084d\"],\"rolesNames\":{\"52bd3ee937361\":\"Sales\",\"52bc41359084d\":\"Sales Manager\"},\"layoutSetId\":\"66d8f8ff4f1c23bca\",\"layoutSetName\":\"Layaout 1\",\"workingTimeCalendarId\":\"66d8f90b424428d1b\",\"workingTimeCalendarName\":\"calendar\"}","statusTrace":"setup_teardown_team = {'createdAt': '2024-09-10 03:46:25', 'deleted': False, 'id': '66dfc111bfc850aa0', 'layoutSetId': '66d8f8ff4f1c23bca', ...}\n\n    @pytest.mark.updateteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_update_team_with_empty_name_returns_400(setup_teardown_team):\n        team1 = setup_teardown_team\n        url = EndpointTeams.get_team_id(team1['id'])\n        data = create_team_data(\n            name=\"\")\n        response = TeamService.update_team(url, data)\n>       AssertionManager.assert_status_code_400(response)\n\ntest/teams/test_put_team.py:46: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n        logger.info(f\"Validating status code 400 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 400, (\n                f\"Expected status code 400, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 400, but got 200. Response text: {\"id\":\"66dfc111bfc850aa0\",\"name\":null,\"deleted\":false,\"positionList\":[\"Qa\",\"Designer\",\"Product Owner\"],\"createdAt\":\"2024-09-10 03:46:25\",\"modifiedAt\":\"2024-09-10 03:46:26\",\"rolesIds\":[\"52bd3ee937361\",\"52bc41359084d\"],\"rolesNames\":{\"52bd3ee937361\":\"Sales\",\"52bc41359084d\":\"Sales Manager\"},\"layoutSetId\":\"66d8f8ff4f1c23bca\",\"layoutSetName\":\"Layaout 1\",\"workingTimeCalendarId\":\"66d8f90b424428d1b\",\"workingTimeCalendarName\":\"calendar\"}\n\ncore/assertions/status_code_assertion.py:37: AssertionError","steps":[],"attachments":[{"uid":"d7ea7a89eac72ccb","name":"log","source":"d7ea7a89eac72ccb.txt","type":"text/plain","size":4626},{"uid":"30aa8d6fbc6b29c","name":"stderr","source":"30aa8d6fbc6b29c.txt","type":"text/plain","size":4845}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[{"name":"setup_teardown_team::0","time":{"start":1725939986215,"stop":1725939986543,"duration":328},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_team::0","time":{"start":1725940008719,"stop":1725940009071,"duration":352},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"updateteam"},{"name":"parentSuite","value":"test.teams"},{"name":"suite","value":"test_put_team"},{"name":"host","value":"fv-az1272-901"},{"name":"thread","value":"2128-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.teams.test_put_team"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["updateteam","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"dd6c484b120c6d6b.json","parameterValues":[]}